---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 600

  roles:
    - configure-server