---
- name: "copy files from CircleCI to server"
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: "install package dependencies"
  shell: |
    cd /home/ubuntu/backend    
    npm install

- name: "build package"
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm run build

- name: "run migrations again"
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm run migrations

- name: run server
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm -- run "start:prod"